Cargohub/controllers/itemlinecontroller.cs, Cargohub/services/Iitemlineservices.cs, Cargohub/services/itemlineservices.cs, tests/itemgroupsTests.cs, tests/itemlinetests.cs
ItemLineController.cs added the CreateMultipleItemLines function and cleaned up some asyncs
IItemLineService.cs added the CreateMultipleItemLines to the interface
ItemLineService.cs added the CreateMultipleItemLines function and cleaned up the asyncs and made it so that AddItemLines now takes the current date for created_At
ItemLineTests.cs Added the CreateMultipleWarehouse_ReturnsCreatedResult_WithNewWarehouse and fixed some tests that weren't working because of the async removals
=> 254 post the system must support bulk posts of item lines records based on specified conditions

V2/tests/clientTest.cs, V2/tests/ordersTests.cs
This pull request includes several changes to test files in the `V2/tests` directory, focusing on improving test coverage and organization. The most important changes include adding a missing assertion in `DeleteClientTest_Success`, setting an additional item in the `HttpContext` for `GetOrdersTest_Exists`, and reorganizing assertions in `GetOrdersTest_Exists`.
Improvements to test coverage and organization:
* [`V2/tests/clientTest.cs`](diffhunk://#diff-7cb832b525707d8ffbb8d665b0afe43bad09000a0045aa3bbbf4753068c743e8R224): Added a missing assertion to the `DeleteClientTest_Success` method.
* [`V2/tests/clientTest.cs`](diffhunk://#diff-7cb832b525707d8ffbb8d665b0afe43bad09000a0045aa3bbbf4753068c743e8L248): Removed an unnecessary closing bracket in the `DeleteClientsTest_Succes` method.
* …
=> Bug fix for the get all orders test

V2/Cargohub/Program.cs, V2/Cargohub/controllers/admincontroller.cs, V2/Cargohub/services/Iadminservice.cs, V2/Cargohub/services/adminservice.cs
This pull request introduces a new feature to handle admin data uploads in the `V2/Cargohub` project. The changes include adding a new service and controller to support uploading and processing `.json` and `.csv` files, converting them to `.json` format, and saving them.
* **Service Registration**:
* Added `IAdminService` and `AdminService` to the service container in `Program.cs`.
* **Admin Controller**:
* Created `AdminController` with an endpoint to handle file uploads, perform authorization checks, and validate file types. The endpoint processes `.json` and `.csv` files, converting and saving them as `.json`.
* **Admin Service Interface**:
* Defined the `IAdminService` interface with a method for adding data from an uploaded file.
* **Admin Service Implementation**:
* Implemented the …
=> 333 the system must allow a user to upload a csv or json file to import their data

V2/Cargohub/controllers/shipmentcontroller.cs
This pull request introduces a new filtering and pagination feature to the `ShipmentController` in the `V2/Cargohub` module. The main changes include the addition of a `shipmentFilter` class and a new endpoint to handle filtered and paginated shipment data.
* Added `shipmentFilter` class: This class includes various properties such as `order_id`, `source_id`, `order_date`, `request_date`, `shipment_date`, `shipment_type`, `shipment_status`, `carrier_code`, `service_code`, `payment_type`, `transfer_mode`, `total_package_count`, and `total_package_weight` to facilitate filtering of shipments.
* New endpoint for filtered and paginated shipments: Introduced a new `GetAllShipments` method that accepts a `shipmentFilter` object and pagination parameters (`page` and `pageSize`). This method …
=> filter plus pagination werkt

PythonTests/test_warehouses.py, V2/Cargohub/controllers/warehousecontroller.cs, V2/tests/warehouseTest.cs
This pull request includes changes to both the Python tests and the C# controller for the warehouse service. The main goals are to update the test cases to handle different API versions and to modify the controller to support pagination and filtering.
* [`PythonTests/test_warehouses.py`](diffhunk://#diff-66c0d65d7fbde9f56762ea4b0409b3903f8c1e51140744fe1f3e4ca11d6c17b2L41-R57): Split the `test_get_warehouses` method into two separate methods, `test_get_warehouses_v1` and `test_get_warehouses_v2`, to test API versions v1 and v2 respectively. The v1 test expects a list response, while the v2 test expects a dictionary response.
* [`V2/Cargohub/controllers/warehousecontroller.cs`](diffhunk://#diff-83013da75da1cf8f6f89d899ecdd9ce1a400f38e904d8eea22bef703b7d3eb15R34-L52): Commented out the …
=> working functionality

.github/workflows/main.yml
This pull request introduces a new scheduled job to the GitHub Actions workflow to perform nightly maintenance. The changes include adding a cron schedule and defining a new job to remove old artifacts.
Changes in GitHub Actions workflow:
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R10-R18): Added a cron schedule to run the workflow every day at 3:00 UTC and defined a new job named `nightly-maintenance` to remove old artifacts.
=> 364 maintenance job on the workflow

.github/workflows/main.yml, PythonTests/test_Clients.py
This pull request includes several changes to the `PythonTests/test_Clients.py` file to improve the handling of client IDs in the test cases. The most important changes involve updating the tests to dynamically fetch the last client ID instead of using hardcoded values.
Improvements to test cases:
* [`test_04_post_client`](diffhunk://#diff-ee4b8cbbbb44afa29488db569813c9a2f633db384aa3cfcdcebc75840216a9a6R42-R72): Moved the test_post_client to the start of the test to ensure that a client is in the database
* [`test_02_get_client_id`](diffhunk://#diff-ee4b8cbbbb44afa29488db569813c9a2f633db384aa3cfcdcebc75840216a9a6R107-R120): Modified the test to dynamically fetch the last client ID so that if would grab the client made in the previous post test.
* …
=> Made it so that the python test is logically structured

PythonTests/test_Inventories.py, V1/Cargohub/Program.cs, V1/Cargohub/Werehouses.csproj, V2/Cargohub/Authentication/ApiKeyMiddleware.cs, V2/Cargohub/Program.cs, V2/Cargohub/Werehouses.csproj, V2/Cargohub/controllers/AdminController.cs
This pull request includes several changes to the `PythonTests/test_Inventories.py` file and various files in the `Cargohub` project to enhance functionality and improve code organization. The most important changes include reordering test methods, adding Swagger documentation support, and updating package references.
Reordering and updating test methods:
* [`PythonTests/test_Inventories.py`](diffhunk://#diff-14e69392283d2a169dedca7a9a729797c3bc679703023831ec79b460d67574a8L12-R12): Reordered the test methods to follow a numerical naming convention and moved `test_get_inventories` and `test_get_inventory_id` to a different location within the file. [[1]](diffhunk://#diff-14e69392283d2a169dedca7a9a729797c3bc679703023831ec79b460d67574a8L12-R12) …
=> 378 swagger docu

.github/workflows/main.yml, .github/workflows/maintenance.yml
This pull request includes changes to the GitHub Actions workflows, specifically moving the nightly maintenance job to a new workflow file.
Changes to GitHub Actions workflows:
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L10-L18): Removed the `schedule` trigger and the `nightly-maintenance` job.
* [`.github/workflows/maintenance.yml`](diffhunk://#diff-6eb5da11d7badb128a54d987e293ca9eec3cbb461d01a0abeae2d7a09675aefbR1-R10): Added a new workflow file for daily maintenance with a `schedule` trigger and the `nightly-maintenance` job.
=> 383 seperate the maintenance into its own yaml file from main yaml file

PythonTests/test_Clients.py, PythonTests/test_Inventories.py
This pull request includes several changes to the `PythonTests/test_Inventories.py` file to improve the test suite for inventory operations. The changes primarily focus on renaming test methods for better organization and ensuring tests dynamically use the last inventory ID.
Improvements to test method organization:
* Renamed test methods to follow a sequential naming convention, improving readability and organization. (`test_01_post_inventory`, `test_02_get_inventories`, `test_03_get_inventory_id`, `test_04_put_inventory_id`, `test_05_delete_inventory_id`) [[1]](diffhunk://#diff-14e69392283d2a169dedca7a9a729797c3bc679703023831ec79b460d67574a8L33-R56) [[2]](diffhunk://#diff-14e69392283d2a169dedca7a9a729797c3bc679703023831ec79b460d67574a8L66-R100)
Enhancements to inventory ID handling:
* …
=> 377 test inventoriespy sorted the test in the right order

PythonTests/test_Items.py, V2/Cargohub/controllers/ItemController.cs
This pull request includes significant updates to the `PythonTests/test_Items.py` file to improve the organization and functionality of the tests, as well as changes to the `GetAllItems` method in the `ItemController.cs` file to enhance pagination logic.
* **Reorganized Test Methods**: Renamed and reordered test methods to follow a more logical sequence, ensuring that item creation (`test_01_post_item`) occurs before retrieval (`test_02_get_items`), and so on. [[1]](diffhunk://#diff-96283a2153913ad9f1fb6480d22f849e5919c53d0697a2fcd4ccb1fec709cc29L12-R37) [[2]](diffhunk://#diff-96283a2153913ad9f1fb6480d22f849e5919c53d0697a2fcd4ccb1fec709cc29L39-R131)
* **Enhanced Test Coverage**: Added new tests for retrieving item details by ID for both API versions (`test_04_get_item_id_v1` and …
=> fixed the test_items.py order 

PythonTests/test_Warehouses.py, V2/Cargohub/controllers/WarehouseController.cs
This pull request includes significant updates to the `PythonTests/test_Warehouses.py` file and a minor change to the `WarehouseController.cs` file to improve pagination logic. The changes primarily focus on reorganizing and enhancing the test cases for warehouse-related API endpoints.
* [`PythonTests/test_Warehouses.py`](diffhunk://#diff-31631230861705fbb3582b420aae525825a6b612cc8bef95b499d74027187f6eL41-L69): Reorganized the test methods to follow a numerical naming convention and added comments to improve clarity. The test methods now include additional checks for response status codes and data types. [[1]](diffhunk://#diff-31631230861705fbb3582b420aae525825a6b612cc8bef95b499d74027187f6eL41-L69) [[2]](diffhunk://#diff-31631230861705fbb3582b420aae525825a6b612cc8bef95b499d74027187f6eR65-L …
=> 376 ordering warehouse python test in the correct order

PythonTests/test_Clients.py
This pull request adds a new test case to the `PythonTests/test_Clients.py` file. The new test case, `test_06_createV1_getV2_test`, verifies the creation, retrieval, and deletion of a client in different versions of the API.
The most important change is:
* [`PythonTests/test_Clients.py`](diffhunk://#diff-ee4b8cbbbb44afa29488db569813c9a2f633db384aa3cfcdcebc75840216a9a6R231-R286): Added the `test_06_createV1_getV2_test` method to test the full lifecycle of a client, including creation, retrieval, and deletion between different versions.
=> Made the Pytest for creating on V1 and getting on the V2

PythonTests/test_Inventories.py
This pull request adds a new test case to the `PythonTests/test_Inventories.py` file. The new test case verifies the creation of an inventory item using API version 1 and subsequently retrieves and validates the same item using API version 2.
The most important change includes:
* [`PythonTests/test_Inventories.py`](diffhunk://#diff-14e69392283d2a169dedca7a9a729797c3bc679703023831ec79b460d67574a8R103-R160): Added a new test case `test_06_createV1_getV2_test` to create an inventory item using API v1, retrieve it using API v2, and validate the item details.
=> made the create on v1 and get on v2 test

V2/Cargohub/controllers/WarehouseController.cs
This pull request includes a change to the `PatchWarehouse` method in the `WarehouseController` to modify the way the `property` parameter is passed. The most important change is:
* [`V2/Cargohub/controllers/WarehouseController.cs`](diffhunk://#diff-70ec61fbf0bac5d4101ed52879eb083dee641e8b7efd8bd175dd973951bcc78bL215-R216): Changed the `PatchWarehouse` method to accept the `property` parameter from the query string instead of the route.
=> rewrote the warehouse patch to use FromQuery

PythonTests/test_ItemLines.py
This pull request adds a new test to the `PythonTests/test_ItemLines.py` file to ensure compatibility between API versions. The new test verifies that an item line created in version 1 of the API can be retrieved and deleted using version 2 of the API.
Key changes include:
* Added `test_06_create_in_v1_get_and_delete_in_v2` method to test creating an item line in API v1, retrieving it in API v2, and deleting it in API v2.
=> ItemLines pytest create in v1 get & delete in v2 #419

PythonTests/test_ItemGroups.py
This pull request introduces a new test case to ensure compatibility between API versions when creating and deleting item groups. The most important change is the addition of the `test_07_create_in_v1_get_and_delete_in_v2` method in the `PythonTests/test_ItemGroups.py` file.
New test case for cross-version compatibility:
* [`PythonTests/test_ItemGroups.py`](diffhunk://#diff-baf1a30319b779048731c2996c6e86c295db7dd4c48bf35a4a39dd715577dea2R148-R187): Added `test_07_create_in_v1_get_and_delete_in_v2` to verify that an item group created using API version 1 can be retrieved and deleted using API version 2. The test includes creating an item group in v1, retrieving it in v2, and then deleting it in v2.
=> ItemGroups pytest create in v1 get & delete in v2 #423

PythonTests/test_Items.py
This pull request adds a new test case to the `PythonTests/test_Items.py` file. The new test case verifies the creation of an item using the v1 API, retrieves the item using the v2 API, and then deletes the item using the v2 API.
The most important change is:
* Added `test_07_create_in_v1_get_and_delete_in_v2` to test creating an item in v1, retrieving it in v2, and deleting it in v2.
=> Items pytest create in v1 get & delete in v2 #426

V2/Cargohub/controllers/SupplierController.cs, V2/Cargohub/services/ISupplierService.cs, V2/Cargohub/services/SupplierService.cs, V2/tests/SupplierTests.cs
This pull request introduces changes to the `PatchSupplier` method and related tests in the `V2/Cargohub` project. The primary goal of these changes is to modify the `PatchSupplier` method to accept a property name and a new value, allowing for more flexible updates to supplier records.
* [`V2/Cargohub/controllers/SupplierController.cs`](diffhunk://#diff-11d2519a8ba5558d2be0da4e7dedb5be77186354e17987d30accaf3ed268c731L150-R150): Updated the `PatchSupplier` method to accept `property` and `newvalue` parameters instead of a `SupplierCS` object. [[1]](diffhunk://#diff-11d2519a8ba5558d2be0da4e7dedb5be77186354e17987d30accaf3ed268c731L150-R150) [[2]](diffhunk://#diff-11d2519a8ba5558d2be0da4e7dedb5be77186354e17987d30accaf3ed268c731L166-R166)
* …
=> 428 refactor patch endpoint suppliers v2

PythonTests/test_ItemTypes.py, V1/Cargohub/services/ClientService.cs, V1/Cargohub/services/InventoryService.cs, V1/Cargohub/services/ItemGroupService.cs, V1/Cargohub/services/ItemLineServices.cs, V1/Cargohub/services/ItemService.cs, V1/Cargohub/services/ItemTypeService.cs, V1/Cargohub/services/LocationService.cs, V1/Cargohub/services/OrderService.cs, V1/Cargohub/services/ShipmentService.cs, V1/Cargohub/services/SupplierService.cs, V1/Cargohub/services/TransferService.cs, V1/Cargohub/services/WarehouseService.cs, V2/Cargohub/services/InventoryService.cs, V2/Cargohub/services/ItemService.cs, V2/Cargohub/services/OrderService.cs, V2/Cargohub/services/ShipmentService.cs, V2/Cargohub/services/WarehouseService.cs
This pull request focuses on adding timestamp fields (`created_at` and `updated_at`) to various entity creation methods across multiple services. The changes ensure that each new record is timestamped with the current date and time when it is created.
Timestamp addition:
* [`V1/Cargohub/services/ClientService.cs`](diffhunk://#diff-389c822bc649956710e847580434af35412f9a1bf7cabbcc76f61a26dce16d1bR34-R39): Added `created_at` and `updated_at` fields with the current timestamp when creating a new client.
* [`V1/Cargohub/services/InventoryService.cs`](diffhunk://#diff-e5ff49a60c2278668f6e9ba8e6616f0eb98b8fb1f2220eb2a8c69eb1d52bc049L50-L57): Added `created_at` and `updated_at` fields with the current timestamp when creating a new inventory.
* …
=> 424 fixing the created at for all v1 posts

V2/Cargohub/controllers/ItemLineController.cs, V2/Cargohub/services/IItemLineServices.cs, V2/Cargohub/services/ItemLineServices.cs, V2/tests/ItemLineTests.cs
This pull request includes changes to the `PatchItemLine` method in the `ItemLineController`, `ItemLineServices`, and corresponding tests to improve flexibility by allowing updates to specific properties of an `ItemLineCS` object. The most important changes include modifying the method signatures and logic to handle property-specific updates.
Changes to `PatchItemLine` method:
* [`V2/Cargohub/controllers/ItemLineController.cs`](diffhunk://#diff-fbe405a027e617fd45704c6afea615a32a225b73e95a9aa9bb9addfa3e68c79bL192-R192): Updated the `PatchItemLine` method to accept a property name and new value as parameters, and added validation for these parameters. [[1]](diffhunk://#diff-fbe405a027e617fd45704c6afea615a32a225b73e95a9aa9bb9addfa3e68c79bL192-R192) …
=> 432 refactor patch endpoint in itemline v2

PythonTests/test_Orders.py, V2/Cargohub/controllers/ShipmentController.cs
This pull request involves significant updates to the `PythonTests/test_Orders.py` file, particularly focusing on the removal of an order validation function and the addition of a new test case to ensure compatibility between API versions.
Key changes include:
* The `checkOrder` function, which validated the completeness of an order by checking the presence of various fields, has been removed.
* A new test case, `test_09_create_in_v1_get_and_delete_in_v2`, has been added. This test case performs the following operations:
* Creates an order using API version 1.
* Retrieves the created order using API version 2 to ensure compatibility.
* Verifies that the retrieved order data matches the created data.
* Deletes the order using API version 2.
=> Orders pytest create in v1 get & delete in v2 #445

PythonTests/test_Shipments.py
This pull request adds a new test case to the `PythonTests/test_Shipments.py` file. The new test case validates the creation of a shipment in version 1 of the API, retrieving it in version 2, and then deleting it in version 2 to ensure cross-version compatibility.
The most important change includes:
* Added a new test case `test_10_create_in_v1_get_and_delete_in_v2` to validate the creation, retrieval, and deletion of a shipment across different API versions (`v1` and `v2`). This test ensures that a shipment created in `v1` can be accessed and deleted in `v2`.
=> Shipments pytest create in v1 get & delete in v2 

PythonTests/test_Suppliers.py
This pull request adds a new test case to the `PythonTests/test_Suppliers.py` file to verify the creation of a supplier in version 1 of the API and the retrieval and deletion of the same supplier in version 2 of the API.
New test case added:
* [`PythonTests/test_Suppliers.py`](diffhunk://#diff-5fb250dd2763323cebf18e7c4bdd690b62aef91e595248846cb95526cb798610R123-R161): Added `test_07_create_in_v1_get_and_delete_in_v2` to test the creation of a supplier in v1, retrieval in v2, and deletion in v2.
=> Suppliers pytest create in v1 get & delete in v2

V2/Cargohub/controllers/AdminController.cs, V2/Cargohub/services/AdminService.cs, V2/Cargohub/services/IAdminService.cs, V2/tests/AdminTests.cs
This pull request introduces a new feature to delete API keys in the `AdminController` and includes corresponding service and test updates. The most important changes are listed below:
* [`V2/Cargohub/controllers/AdminController.cs`](diffhunk://#diff-5cec75d5797bd939833e7dc967bd5df729480d78a12f2dad24b7bf5a808c03d2R146-R176): Added a new `DeleteAPIKeys` endpoint that allows deletion of API keys, with authorization checks for the "Admin" role.
* [`V2/Cargohub/services/AdminService.cs`](diffhunk://#diff-b99f7b123c3797b85fa1b95bc5bf12e93bc77b6241af3c5020f9e4e8aaec6129R133-R147): Implemented the `DeleteAPIKeys` method to remove API keys from the storage.
* [`V2/Cargohub/services/IAdminService.cs`](diffhunk://#diff-728a85f237c4c3aaa4608605d388cf85d427ee2d6f9ab131b511c15a2a9c7b7aR8): Updated the …
=> created the delete APIkey endpoint

V2/Cargohub/controllers/AdminController.cs, V2/Cargohub/services/AdminService.cs, V2/Cargohub/services/IAdminService.cs, V2/tests/AdminTests.cs
This pull request introduces a new feature to add API keys, along with the necessary backend support and unit tests. The most important changes include adding a new endpoint in the `AdminController`, implementing the corresponding service method, updating the service interface, and adding unit tests to ensure the functionality works as expected.
* [`V2/Cargohub/controllers/AdminController.cs`](diffhunk://#diff-5cec75d5797bd939833e7dc967bd5df729480d78a12f2dad24b7bf5a808c03d2R118-R146): Added a new `AddAPIKeys` endpoint to handle POST requests for adding API keys. This includes role-based authorization and error handling.
* [`V2/Cargohub/services/AdminService.cs`](diffhunk://#diff-b99f7b123c3797b85fa1b95bc5bf12e93bc77b6241af3c5020f9e4e8aaec6129R114-R123): Implemented the `AddAPIKeys` method …
=> 457 the system must provide an endpoint for creating apikeys

V2/tests/ItemGroupTests.cs
This pull request introduces additional test cases to ensure that unauthorized access is properly handled in the `ItemGroupController` methods. Each test case now includes a scenario where the user role is set to "NoRole" to verify that the controller returns a 401 Unauthorized status code.
Key changes include:
* **Unauthorized Access Tests:**
* [`V2/tests/ItemGroupTests.cs`](diffhunk://#diff-a98be35fc72fdd12ddb3a1fe061922aef44e3f3d70f8cf8aafa32d57634acca7R53-R66): Added unauthorized access test to `GetAllItemGroupsTest_Exists()` to check for 401 status code when user role is "NoRole".
* [`V2/tests/ItemGroupTests.cs`](diffhunk://#diff-a98be35fc72fdd12ddb3a1fe061922aef44e3f3d70f8cf8aafa32d57634acca7R94-R107): Added unauthorized access test to `GetItemGroupByIdTest_Exists()` to verify 401 …
=> added the unauthorized checks for the itemgroups

V2/Cargohub/controllers/WarehouseController.cs, V2/tests/WarehouseTests.cs
This pull request introduces authorization checks for the `WarehouseController` and updates the corresponding unit tests to validate these changes. The main focus is ensuring that only users with the "Admin" role can perform certain actions on the warehouse resources.
Authorization checks:
* [`V2/Cargohub/controllers/WarehouseController.cs`](diffhunk://#diff-70ec61fbf0bac5d4101ed52879eb083dee641e8b7efd8bd175dd973951bcc78bR217-R223): Added a check to ensure that only users with the "Admin" role can access the `PatchWarehouse` method. If the user role is not "Admin", the method returns an `Unauthorized` response.
Unit test updates:
* [`V2/tests/WarehouseTests.cs`](diffhunk://#diff-cd37b585a7d77a6542b907edbb2790975c6ccd4f46e494711e9f328a5352456eR52-R66): Updated various test methods to …
=> 466 adding unauthorized testing warehouse

V2/tests/ItemLineTests.cs
This pull request adds new test scenarios to the `ItemLineTests` class in `V2/tests/ItemLineTests.cs` to verify the behavior of the `ItemLineController` when the user role is unauthorized. The changes ensure that appropriate unauthorized responses are returned when the user role is not permitted to perform certain actions.
New test scenarios for unauthorized access:
* Added checks in `GetItemLinesTest_Exists` to verify that the controller returns a 401 Unauthorized status when the user role is unauthorized.
* Updated `GetItemLineByIdTest_Exists` to include a scenario where an unauthorized user role results in a 401 Unauthorized status.
* Modified `GetItemLineByIdTest_WrongId` to test for unauthorized access and ensure a 401 Unauthorized status is returned.
* Added unauthorized user role …
=> 475 item line unauthorized laten checken

V2/tests/SupplierTests.cs
This pull request adds authorization checks to various test methods in the `V2/tests/SupplierTests.cs` file. The changes ensure that unauthorized access is correctly handled by the `SupplierController`.
Authorization checks:
* Added `UserRole` to `httpContext.Items` and set the `ControllerContext` for `_supplierController` in `GetSuppliersTest_Exists()` to verify unauthorized access handling.
* Added `UserRole` to `httpContext.Items` and set the `ControllerContext` for `_supplierController` in `GetSupplierByIdTest_Exists()` to verify unauthorized access handling.
* Added `UserRole` to `httpContext.Items` and set the `ControllerContext` for `_supplierController` in `GetSupplierByIdTest_WrongId()` to verify unauthorized access handling.
* Added `UserRole` to `httpContext.Items` and set the …
=> all unauthorization test in suppliers

V2/Cargohub/controllers/OrderController.cs, V2/tests/OrderTests.cs
This pull request introduces authorization checks based on user roles in the `OrderController` and updates the corresponding test cases to validate the new authorization logic.
* [`V2/Cargohub/controllers/OrderController.cs`](diffhunk://#diff-64160721919de2ca496be5024a81d25241aec859c3af30e385eff19e07f60e8cR292-R299): Added a list of allowed roles and implemented a check to ensure that only users with specific roles can access the `PatchOrder` method. Unauthorized users will receive a 401 status code.
* [`V2/tests/OrderTests.cs`](diffhunk://#diff-fc9ae0990cd6edc53f8471f1381331d42c0ae4d4b3e83917532c70ab3c808966R53-R66): Updated multiple test methods to include scenarios where the `UserRole` is set to an unauthorized role ("Soldier"). These tests now verify that the controller methods return …
=> order unauthorized test

V2/Cargohub/controllers/ItemTypeController.cs, V2/Cargohub/services/IItemTypeService.cs, V2/Cargohub/services/ItemTypeService.cs, V2/tests/ItemTypeTests.cs
This pull request includes several changes to the `ItemTypeController`, `IItemTypeService`, `ItemTypeService`, and related test files to improve authorization checks and switch from asynchronous to synchronous methods. The most important changes include updating the `UpdateItemType` method to be synchronous, adding authorization checks, and modifying the tests to reflect these changes.
Authorization checks:
* [`V2/Cargohub/controllers/ItemTypeController.cs`](diffhunk://#diff-5d508b0fe806e9b72bd622dbfbf7b983c878d74fa4159e6a1d856c90d2cb6cf5L125-R165): Added authorization checks to ensure that only users with specific roles can perform certain actions.
Switch from asynchronous to synchronous methods:
* [`V2/Cargohub/services/IItemTypeService.cs`](diffhunk://#diff-85298a48ac2f915a665208b2a493e …
=> Removed all async with itemtype did all unauth tests

V2/tests/ItemGroupTests.cs, V2/tests/ItemTests.cs, V2/tests/ItemTypeTests.cs, V2/tests/LocationTests.cs
This pull request includes significant changes to the `ClientService`, `ItemGroupService`, and their respective tests to improve functionality and add new test cases. Additionally, the GitHub Actions workflow has been updated to trigger on both push and pull request events.
* [`V2/Cargohub/services/ClientService.cs`](diffhunk://#diff-3070681823f3002acdd8ee205982a0efcbcb080100daaa5261ff23d674fab525L64-R64): Changed the method to find clients by using `FirstOrDefault` instead of `Single` to handle cases where no matching client is found.
* [`V2/tests/ClientTests.cs`](diffhunk://#diff-c6ad61f58fb4d4f49de621acc3371472b3d8c7723b77535b49cecfe9c0855518R428-R640): Added comprehensive test cases for `ClientService` methods including `GetAllClientsService_Test`, `GetClientByIdService_Test`, …
=> 505 increasing code coverage for itemstests v2 and ItemGroupServices

V2/tests/ItemGroupTests.cs, V2/tests/ItemLineTests.cs, V2/tests/ItemTests.cs
This pull request includes several changes to the test files in the `V2/tests` directory. The most significant changes involve adding new test methods for the `ItemLineService` and updating existing assertions. Additionally, a new dependency was added to the `ItemLineTests.cs` file.
**Test Enhancements:**
* [`V2/tests/ItemLineTests.cs`](diffhunk://#diff-08e3c5ab9a57bf514b8e5ccaaca1538c5795c58d86ae4d8aa53fbefa326aca92R585-R726): Added multiple new test methods for `ItemLineService`, including tests for creating, updating, deleting, and patching item lines. These methods ensure comprehensive coverage of the service's functionality.
* [`V2/tests/ItemLineTests.cs`](diffhunk://#diff-08e3c5ab9a57bf514b8e5ccaaca1538c5795c58d86ae4d8aa53fbefa326aca92R24-R37): Updated the `Setup` method to include …
=> 508 increasing code coverage on itemlineservice v2

.github/workflows/main.yml, V2/tests/ItemTypeTests.cs
This pull request includes updates to the GitHub Actions workflow and enhancements to the unit tests for item types. The most important changes include removing the push trigger from the GitHub Actions workflow and adding several new test methods to the `ItemTypeTests` class.
Enhancements to GitHub Actions workflow:
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L7-L9): Removed the `push` trigger to streamline the workflow and only trigger actions on pull requests.
Enhancements to unit tests:
* [`V2/tests/ItemTypeTests.cs`](diffhunk://#diff-5250baebbabfd139dea880ebb6a7d9b34a36c23102c67243a71ad51331624e64L33-R33): Updated the `Setup` method to change the `Name` property of the `itemType` object.
* …
=> Increased the coverage for ItemTypeService V2

V1/tests/InventoryTests.cs
This pull request includes significant changes to the `V1/tests/InventoryTests.cs` file, mainly focusing on enhancing the test coverage for the inventory service. The changes involve adding new test methods, creating mock data for testing, and ensuring proper setup for the tests.
Enhancements to test coverage:
* Added necessary imports for JSON handling and test platform object model. (`V1/tests/InventoryTests.cs`)
* Created mock inventory data and wrote it to a JSON file during the setup phase to facilitate testing. (`V1/tests/InventoryTests.cs`)
New test methods:
* Added `GetAllInventoriesService_Test_Succes` to test the retrieval of all inventories. (`V1/tests/InventoryTests.cs`)
* Added `GetInventoryById_Test_Succes` to test the retrieval of an inventory by its ID. …
=> inventoriestest v1 done

V2/Cargohub/services/SupplierService.cs, V2/tests/SupplierTests.cs, V2/tests/TransferTests.cs
This pull request includes several changes to the `SupplierService` and its corresponding tests in the `SupplierTests` file. The most important changes include updating the method for fetching a supplier by ID, adding new test methods for various supplier services, and initializing test data for suppliers.
Updates to `SupplierService`:
* [`V2/Cargohub/services/SupplierService.cs`](diffhunk://#diff-133e2935af7375fbe2079721d1770a296906f335b69d20fec274c1791f5c71bcL62-R62): Changed `Single` to `SingleOrDefault` in the `UpdateSupplier` method to handle cases where no supplier is found.
Enhancements to `SupplierTests`:
* [`V2/tests/SupplierTests.cs`](diffhunk://#diff-3d93140d6bdf8d2b2b6571ec6542ca906884c46966479b65948ec6089eeea7bfR8): Added `Newtonsoft.Json` to handle JSON serialization for …
=> 524 code coverage suppliers v2

V2/tests/ClientTests.cs
This pull request introduces several new test methods to the `V2/tests/ClientTests.cs` file, focusing on handling various error cases for the client-related endpoints. The most important changes include adding tests for `NotFound` and `BadRequest` responses in different scenarios.
New test methods for error handling:
* Added `GetAllClients_Test_returns_NotFound` to handle the case when no clients are found.
* Added `GetClientById_Test_returns_NotFound` to handle the case when a client with a specific ID is not found.
* Added `CreateClient_ReturnsCreatedResult_WithoutClient` to handle the case when a null client is provided.
* Added `CreateMultipleClient_ReturnsCreatedResult_WithoutClients` to handle the case when a null list of clients is provided.
* Added …
=> updated the ClientController code coverage

V1/tests/WarehouseTest.cs
This pull request includes several updates to the `V1/tests/WarehouseTest.cs` file, primarily focusing on setting up test data and adding new test methods for various warehouse service functionalities.
* Added initialization of a sample warehouse and writing it to a JSON file in the `Setup` method.
* Added `GetAllWarehousesService_Test` to verify retrieval of all warehouses.
* Added `GetWarehouseByIdService_Test` to verify retrieval of a warehouse by its ID.
* Added `CreateWarehouseService_Test` to verify the creation of a new warehouse.
* Added `CreateMultipleWarehouseService_Test` to verify the creation of multiple warehouses.
* Added `UpdateWarehouseService_Test` to verify updating an existing warehouse.
* Added `DeleteWarehouseService_Test` to verify deletion of a warehouse.
* Added …
=> Increasing code coverage for Warehouse v1

V1/Cargohub/services/OrderService.cs, V1/tests/OrderTests.cs, V2/tests/OrderTests.cs
This pull request includes several changes to the `OrderService` and its corresponding tests to improve functionality and test coverage. The most important changes include modifying the `GetOrdersByClient` method, adding new test cases, and updating the test setup to include JSON data.
* [`V1/Cargohub/services/OrderService.cs`](diffhunk://#diff-f5e0b52d04fb8818808ea4b6ad492db58c30036bcbeda33d1bd44137f2b2b5efL53-R53): Updated the `GetOrdersByClient` method to return `null` only if the `clientOrders` list is empty instead of checking for `null`.
* [`V1/tests/OrderTests.cs`](diffhunk://#diff-b84f64fdda9d39f7da7b0ae567fe2f8008bf267d9311ea8c02951eb2d26ec589R7): Added the `Newtonsoft.Json` import and updated the `Setup` method to create a JSON file with order data for testing purposes. …
=> 542 order service v1 tests coverage

V1/Cargohub/services/SupplierService.cs, V1/tests/SupplierTests.cs
This pull request includes significant updates to the `V1/tests/SupplierTests.cs` file, focusing on adding new test methods for the `SupplierService` and setting up initial data for tests.
* Added `GetAllSuppliersService_Test` to verify that the `GetAllSuppliers` method returns the correct number of suppliers.
* Added `GetSupplierByIdService_Test` to check if the `GetSupplierById` method retrieves the correct supplier details.
* Added `CreateSupplierService_Test` to test the creation of a new supplier and verify the updated list of suppliers.
* Added `UpdateSupplierService_Test` to test updating an existing supplier and ensure the changes are correctly applied.
* Added `DeleteSupplierService_Test` and `DeleteSupplierService_FailTest` to test the deletion of a supplier and handle cases …
=> Increasing code coverage for Suppliers v1

V1/Cargohub/services/LocationService.cs, V1/tests/LocationTests.cs, V2/tests/LocationTests.cs
This pull request includes several changes to the `LocationService` and its corresponding tests. The most important changes involve improvements to the `LocationService` methods and the addition of new unit tests to ensure the service functions correctly.
* Changed `UpdateLocation` method to use `SingleOrDefault` instead of `Single` to handle cases where the location might not be found. (`V1/Cargohub/services/LocationService.cs`)
* Modified `DeleteLocation` method to remove a location only if it exists, fixing the conditional check. (`V1/Cargohub/services/LocationService.cs`)
* Added `Newtonsoft.Json` import to `LocationTests.cs` to handle JSON operations. (`V1/tests/LocationTests.cs`)
* Enhanced `Setup` method in `LocationTests.cs` to initialize test data by writing a sample location to …
=> 550 location service v1 coverage tests

V1/tests/InventoryTests.cs
This pull request includes several changes to the `V1/tests/InventoryTests.cs` file to improve the naming consistency of test methods and add new test cases. The most important changes include renaming existing test methods, adding tests for empty list scenarios, and adding failure cases for update and delete operations.
* Renamed `GetInventoryById_Test_Succes` to `GetInventoryByIdService_Test_Succes` to maintain consistent naming conventions.
* Renamed `GetInventoriesForItem_Test_Succes` to `GetInventoriesForItemService_Test_Succes`.
* Renamed `CreateInventory_Test_Succes` to `CreateInventoryService_Test_Succes`.
* Renamed `UpdateInventoryById_Test_Succes` to `UpdateInventoryByIdService_Test_Succes`.
* Added `CreateInventoryService_Test_EmptyListFirst` to test creating an inventory when …
=> fail tests added

V2/tests/ItemTypeTests.cs
This pull request includes several additions and modifications to the `ItemTypeTests.cs` file to enhance the test coverage for the `ItemTypeController`. The changes include adding new test methods for various scenarios and a minor formatting fix.
New test methods added:
* Added `GetAllItemtypes_ShouldReturnOkResult_WithItemTypes` to verify that the `GetAllItemtypes` method returns an OK result with the expected item types.
* Added `GetAllItemtypes_ShouldReturnUnauthorized_WhenUserRoleIsInvalid` to ensure that the `GetAllItemtypes` method returns an Unauthorized result when the user role is invalid.
* Added `CreateMultipleItemTypes_ShouldReturnCreatedItemTypes` to test that the `CreateMultipleItemTypes` method returns the created item types with a Created status.
* Added …
=> Increasing the code coverage for ItemTypeController

V1/Cargohub/services/ItemTypeService.cs, V1/tests/ItemTypeTests.cs
This pull request includes changes to the `ItemTypeService` and its associated tests to improve functionality and add new test cases. The most important changes include fixing a logical error in the `DeleteItemType` method, adding new test cases for the `UpdateItemTypeService` method, and minor code cleanup.
* Fixed the logical error in the `DeleteItemType` method by changing the condition to check if the item is not null before attempting to remove it. (`V1/Cargohub/services/ItemTypeService.cs`)
* Added `UpdateItemTypeService_Test_Failed` to verify the behavior of the `UpdateItemTypeService` method when an invalid ID is provided. (`V1/tests/ItemTypeTests.cs`)
* Removed unnecessary blank lines in the `Setup` method. (`V1/tests/ItemTypeTests.cs`)
* Added missing `using …
=> 556 item type v1 service code coverage

V1/tests/ItemTypeTests.cs, V2/tests/ItemTypeTests.cs
This pull request includes several updates to the test cases in the `V1/tests/ItemTypeTests.cs` and `V2/tests/ItemTypeTests.cs` files to enhance the coverage and accuracy of the tests. The changes include modifications to existing tests, the addition of new tests, and the removal of redundant tests.
* Updated `GetAllItemtypes_ShouldReturnAllItemTypes` to use the controller method and assert the result is not null before checking the count. (`V1/tests/ItemTypeTests.cs`, [V1/tests/ItemTypeTests.csL56-R61](diffhunk://#diff-2ceea928452289a96eabf6fbacabf555e21d5f25354868fad24a94cc5eb9ba7dL56-R61))
* Updated `GetItemById_ShouldReturnCorrectItemType` to use the controller method and assert the result is not null before comparing the returned item. (`V1/tests/ItemTypeTests.cs`, …
=> 563 increasing the code coverage for itemtypecontroller 2
