Jasper85125/Werehouses

api/providers/data_provider.py
=> fixed the root_path

Cargohub/controllers/warehousecontroller.cs, Cargohub/services/Iwarehouseservice.cs, Cargohub/services/warehouseservice.cs, tests/warehouseTest.cs
=> 28 get the system must allow users to fetch a specific warehouse record by ids

Cargohub/controllers/itemlinecontroller.cs, Cargohub/services/Iitemlineservices.cs, Cargohub/services/itemlineservices.cs, Cargohub/services/warehouseservice.cs, tests/itemlinetests.cs
- Refactored the `PostItemLine` method in the `ItemLineController` to use the `ItemLineCS` model instead of a string parameter.
- Updated the `AddItemLine` method in the `ItemLineService` to handle the addition of a new item line.
- Added unit tests for the `AddItemLine` method in the `ItemLineTests` class.
Closes #72
=> Refactor item line controller and service

Cargohub/controllers/locationcontroller.cs, Cargohub/controllers/suppliercontroller.cs, Cargohub/services/Isupplierservice.cs, Cargohub/services/supplierservice.cs, tests/suppliersTests.cs
Made the CreateSupplier and CreateSupplierTest
=> 89 post the system must allow users to create new supplier records

api/tests/test_clients.py, api/tests/test_inventories.py, api/tests/test_item_groups.py, api/tests/test_item_lines.py, api/tests/test_item_types.py, api/tests/test_items.py, api/tests/test_locations.py, api/tests/test_orders.py, api/tests/test_shipments.py, api/tests/test_suppliers.py, api/tests/test_transfers.py, api/tests/test_warehouses.py
made some test for when data is missing from body and if id is non_existing for all test files
=> Some integration tests I believe?

Cargohub/controllers/inventorycontroller.cs, Cargohub/services/Iiventoryservice.cs, Cargohub/services/inventoryservice.cs, tests/inventoryTest.cs
the test file probbaly doesn't work yet.
=> (POST) The system must allow users to create new inventory records. #92

Cargohub/controllers/suppliercontroller.cs, Cargohub/services/Isupplierservice.cs, Cargohub/services/supplierservice.cs, tests/suppliersTests.cs
files changed 
suppliercontroller
supplierservice
isupplierservice
suppliertests
=> 191 get the system must allow users to fetch all item records for a specific supplier

Cargohub/controllers/itemtypecontroller.cs, Cargohub/services/Iitemservice.cs, Cargohub/services/itemservice.cs, tests/itemsTests.cs, tests/itemtypesTests.cs
itemtypecontroller.cs made the GetAllItemsInItemType
IItemService.cs added the GetAllItemsInItemType method to the interface
ItemService.cs added the GetAllItemsInItemType method
ItemsTests made the GetItemsWithItemType_Success method
ItemTypeTests added some fields so it reflects the new situations
=> 193 get the system must allow users to fetch all item records in a specific item type

Cargohub/controllers/itemlinecontroller.cs, Cargohub/services/Iitemlineservices.cs, Cargohub/services/itemlineservices.cs, tests/itemlinetests.cs
itemlineservice: i have added the function that gets all the items that have a given item line
Iitemlineservice: added an interface to get the function
itemlinecontroller: added the controller for the function
itemlinetest: added a test for the function
=> 206 getthe system must allow users to fetch all item records in a specific item line

.github/workflows/csharp-app.yml
=> made the yml file

Cargohub/controllers/warehousecontroller.cs, Cargohub/services/Iwarehouseservice.cs, Cargohub/services/warehouseservice.cs, tests/warehouseTest.cs
WarehouseController.cs added CreateMultipleWarehouse function
IWarehouseService.cs added List<WarehouseCS> CreateMultipleWarehouse(List<WarehouseCS>newWarehouse); to the interface
WarehouseService.cs added CreateMultipleWarehouse function
WarehouseTest.cs added the CreateMultipleWarehouse_ReturnsCreatedResult_WithNewWarehouse test
=> 219 postthe system must support bulk posts of warehouse records based on specified conditions

Cargohub/controllers/clientcontroller.cs, Cargohub/controllers/warehousecontroller.cs, Cargohub/services/Iclientservice.cs, Cargohub/services/clientservice.cs, tests/clientTest.cs
ClientController.cs Added the CreateMultipleClients function
ClientService.cs Added the CreateMulitpleClients function and updated the CreateClient so that it fills in the created_at with the current date
IClientService.cs added the CreateMultipleClients to the interface
ClientTest.cs added the CreateMultipleClient_ReturnsCreatedResult_WithNewClient
=> Made the bulk post for Clients and made the test for it

Cargohub/controllers/itemlinecontroller.cs, Cargohub/services/Iitemlineservices.cs, Cargohub/services/itemlineservices.cs, tests/itemlinetests.cs
added batch delete of item lines and a test for it.
Files changed:
itemlinestest.cs
itemlineservice.cs
Iitemlineservice.cs
itemlinecontroller.cs
=> test and function in 1 go

Cargohub/controllers/itemgroupcontroller.cs, Cargohub/services/Iitemgroupservice.cs, Cargohub/services/itemgroupservice.cs, Cargohub/services/itemtypeservice.cs, tests/itemgroupsTests.cs
added a patch for the controller and service
Files changed:
Iitemgroupservice.cs
itemgroupservice.cs
itemgroupsTests.cs
itemgroupcontroller.cs
=> 225 patch the system should be able to modify item groups based on their

Cargohub/controllers/inventorycontroller.cs, Cargohub/services/Iiventoryservice.cs, Cargohub/services/inventoryservice.cs, tests/inventoryTest.cs
InventoryController.cs added the CreateMultipleInventories method
InventoryService.cs added the CreateMultipleInventories method and made it so that the CreateInventory takes the current date for the created_at field
IInventoryService.cs added the CreateMultipleInventories to the interface
InventoryTest.cs added the CreateMultipleInventories_ReturnsCreatedResult_WithNewInventories test
=> 223 postthe system must support bulk posts of inventories records based on specified conditions

Cargohub/controllers/itemtypecontroller.cs, Cargohub/services/Iitemtypeservice.cs, Cargohub/services/itemtypeservice.cs, tests/itemtypesTests.cs
added batch delete function for item types and a test for it.
Files changed:
itemtypecontroller.cs
Iitemtypeservice.cs
itemtypeservice.cs
itemtypesTests.cs
=> 234 delete the system must support bulk deletion of item types records based on specified conditions

Cargohub/controllers/itemgroupcontroller.cs, Cargohub/services/Iitemgroupservice.cs, Cargohub/services/itemgroupservice.cs, tests/itemgroupsTests.cs
Itemgroupcontroller.cs added CreateMultipleItemGroups function
Itemgroupservice.cs added CreateMultipleItemGroups function
IItemGroupService.cs added the CreateMultipleItemGroups to the interface
Itemgroupstests added the  CreateMultipleWarehouse_ReturnsCreatedResult_WithNewWarehouse test
=> 239 postthe system must support bulk posts of item groups records based on specified conditions

Cargohub/controllers/ordercontroller.cs, Cargohub/services/Iorderservice.cs, Cargohub/services/orderservice.cs, tests/ordersTests.cs
added batch delete for orders and a test for it. 
Files Changed:
ordersTest.cs
orderservice.cs
Iorderservice.cs
ordercontroller.cs
=> 244 delete the system must support bulk deletion of orders records based on specified conditions

Cargohub/controllers/shipmentcontroller.cs, Cargohub/services/Ishipmentservice.cs, Cargohub/services/shipmentservice.cs, tests/shipmentsTests.cs
added batch delete of shipments function. and the test for it. 
files changed:
shipmentcontroller.cs
shipmentservices.cs
Ishipmentservice.cs
shipmentTest.cs
=> function + test

Cargohub/controllers/suppliercontroller.cs, Cargohub/services/Isupplierservice.cs, Cargohub/services/supplierservice.cs, tests/suppliersTests.cs
added batch deletion function of suppliers and a test.
Files changed:
suppliersTest.cs
supplierservice.cs
Isupplierservice.cs
suppliercontroller.cs
=> 248 delete the system must support bulk deletion of suppliers records based on specified conditions

Cargohub/controllers/transfercontroller.cs, Cargohub/services/Itransferservice.cs, Cargohub/services/transferservice.cs, tests/TransfersTests.cs
Added batch delete function for transfers and a test.
Files changed:
TransfersTest.cs
Itransferservice.cs
transferservice.cs
transfercontroller.cs
=> function plus test works

Cargohub/controllers/itemcontroller.cs, Cargohub/services/Iitemservice.cs, Cargohub/services/itemservice.cs, tests/itemsTests.cs
Itemcontroller: added DeleteMultipleItems function
IItemservice: added DeleteItems in the interface
Itemservice: added DeleteItems function
ItemTest: added the Test DeleteItems_ReturnsOkResult_WhenItemsAreDeleted
=> 240 delete the system must support bulk deletion of items records based on specified conditions

Cargohub/controllers/locationcontroller.cs, Cargohub/services/Ilocationservice.cs, Cargohub/services/locationservice.cs, tests/itemgroupsTests.cs, tests/locationsTests.cs
LocationController.cs added CreateMultipleLocations function
ILocationService.cs added CreateMultipleLocations to the interface
LocationService.cs added CreateMultipleLocations function
LocationTest.cs added the CreateMultipleLocations_ReturnsCreatedResult_WithNewLocations test
ItemGroupTest.cs small tweak to a function name
=> 256 post the system must support bulk posts of locations records based on specified conditions

Cargohub/controllers/ordercontroller.cs, Cargohub/services/Iorderservice.cs, Cargohub/services/orderservice.cs, tests/ordersTests.cs
OrderController.cs added the CreateMultipleOrders function
OrderService.cs added the CreateMultipleOrders function
IOrderService.cs added CreateMultipleOrders to the interface
OrderTests.cs added the CreateMultipleOrders_ReturnsCreatedResult_WithNewOrders test
=> 259 post the system must support bulk posts of orders records based on specified conditions

Cargohub/controllers/transfercontroller.cs, Cargohub/services/Itransferservice.cs, Cargohub/services/transferservice.cs, tests/TransfersTests.cs
TransfersController.cs added CreateMultipleTransfers function
TransfersService.cs added CreateMultipleTransfers function and fixed the createTransfer so that the created_at gives the current date
ITransfersService.cs added CreateMultipleTransfers to the interface
TransfersTests.cs added the CreateMultipleTransfers_ReturnsCreatedResult_WithNewTransfers test
=> 261 post the system must support bulk posts of transfers records based on specified conditions

Cargohub/controllers/itemgroupcontroller.cs, Cargohub/controllers/itemlinecontroller.cs, Cargohub/services/Iitemlineservices.cs, Cargohub/services/itemlineservices.cs, tests/itemlinetests.cs
added the patch
Files changed:
itemlinestest.cs
itemlineservice.cs
Iitemlineservice.cs
itemlinecontroller.cs
=> 236 patch the system should be able to modify item lines based on their

V2/Cargohub/controllers/shipmentcontroller.cs, V2/Cargohub/services/Ishipmentservice.cs, V2/Cargohub/services/shipmentservice.cs, V2/tests/shipmentsTests.cs
In this pull request I have made the methodes for bulk posting of shipments. I have also made the corresponding test for this function.
Shipmentcontroller.cs made the CreateMultipleShipments
Ishipmentservice.cs added CreateMultipleShipments to the interface
Shipmentservice.cs made the CreateMultipleShipments
ShipmentTests.cs made the CreateMultipleShipments_ReturnsCreatedResult_WithNewShipments
=> made the bulk post for shipments

V2/Cargohub/controllers/itemcontroller.cs, V2/Cargohub/services/Iitemservice.cs, V2/Cargohub/services/itemservice.cs, V2/tests/itemsTests.cs
item controller kan nu patch requests ontvangen.
item service kan het request verwerken.
item test, test de ontvangen en verweken van de request.
=> 311 patch the system should be able to modify items based on their

V2/Cargohub/controllers/warehousecontroller.cs, V2/Cargohub/services/Iwarehouseservice.cs, V2/Cargohub/services/warehouseservice.cs, V2/tests/warehouseTest.cs
warehouse controller kan patch requests ontvangen.
warehouse service kan de request verwerken. 
warehouse test, test de ontvangen en verwerken van de request.
=> 309 warehouses patching

V2/Cargohub/controllers/itemtypecontroller.cs, V2/Cargohub/services/Iitemtypeservice.cs, V2/Cargohub/services/itemtypeservice.cs, V2/tests/itemtypesTests.cs
itemtype controller ontvangt patch requests
itemtype service verwerkt de request
itemtype test, test beide.
=> 314 patch the system should be able to modify item types based on their

.github/workflows/main.yml, PythonTests/requirements.txt, PythonTests/test_clients.py, PythonTests/test_inventories.py, PythonTests/test_item_groups.py, PythonTests/test_item_lines.py, PythonTests/test_item_types.py, PythonTests/test_items.py, PythonTests/test_locations.py, PythonTests/test_orders.py, PythonTests/test_shipments.py, PythonTests/test_suppliers.py, PythonTests/test_transfers.py, PythonTests/test_warehouses.py, V1/Cargohub/Program.cs, V2/Cargohub/Program.cs, V2/Cargohub/controllers/clientcontroller.cs, V2/Cargohub/services/Iclientservice.cs, V2/Cargohub/services/clientservice.cs, V2/tests/clientTest.cs
This pull request includes changes to improve the testing and build processes for multiple versions of the application. The most important changes include modifications to the GitHub Actions workflow, updates to the test cases to handle multiple API versions, and improvements in code consistency.
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L99-R103): Updated the `Run application` step to build and run both `V1` and `V2` versions of the `Cargohub` project.
* [`PythonTests/test_clients.py`](diffhunk://#diff-302dd90f24faeb5ddf0cf51e283693493bb9777ff01db0472fa1cb72d95ab8a9L10-R30): Modified test cases to handle multiple API versions by iterating over versions and using `subTest` for better test isolation. …
=> 310 patch the system should be able to modify clients based on their

V2/Cargohub/controllers/admincontroller.cs
This pull request adds a new endpoint to the `admincontroller.cs` file to allow authorized users to download files from the server. The most important changes include the addition of the `GetData` method, which handles the file retrieval and authorization process.
New endpoint for file retrieval:
* [`V2/Cargohub/controllers/admincontroller.cs`](diffhunk://#diff-7247e1784917113b8c7038bd3343763ddd4a6faff48910c3bc6e5c60ab04129eR56-R82): Added the `GetData` method to handle HTTP GET requests for downloading files. This method includes role-based authorization to ensure only users with the "Admin" role can access the files, constructs the file path, checks if the file exists, and returns the file with the appropriate content disposition.
=> created a function that lets an admin download the requested file

V2/Cargohub/controllers/itemcontroller.cs, V2/Cargohub/models/page.cs
This pull request includes several changes to the `V2/Cargohub/controllers/itemcontroller.cs` file and the addition of a new pagination model. The most important changes include the creation of a new `itemFilter` class, the implementation of a paginated and filtered `GetAllItems` endpoint, and the addition of a new `PaginationCS` class.
Improvements to item filtering and retrieval:
* [`V2/Cargohub/controllers/itemcontroller.cs`](diffhunk://#diff-10d20dd6649e70fb1da4e0ebdcd3e8431fcf42f8407f17028bf186bfcf21387fR7-R21): Added a new `itemFilter` class to allow filtering of items based on various properties, with several properties changed to nullable.
* [`V2/Cargohub/controllers/itemcontroller.cs`](diffhunk://#diff-10d20dd6649e70fb1da4e0ebdcd3e8431fcf42f8407f17028bf186bfcf21387fR36-R179): …
=> 334 implimenteer een filter voor item

V2/Cargohub/controllers/inventorycontroller.cs
This pull request introduces a new filtering and pagination functionality to the `InventoryController` in the `V2/Cargohub` project. The key changes include the addition of a new `inventoryFilter` class, and a new endpoint to handle paginated and filtered inventory data.
* Added a new `inventoryFilter` class to define the filter criteria for inventories. This class includes properties such as `Id`, `item_id`, `LocationsCount`, `total_on_hand`, `total_expected`, `total_ordered`, `total_allocated`, and `total_available`.
* Introduced a new endpoint `GetAllItems` in the `InventoryController` that supports pagination and filtering of inventory data. This endpoint checks user roles for authorization, filters the inventories based on the provided filter criteria, and implements pagination logic …
=> working filter plus pagination

V2/Cargohub/controllers/warehousecontroller.cs
This pull request introduces a new filtering and pagination feature for the Warehouse API in the `WarehouseController` class. The most important changes include the addition of a new filter class and a new endpoint for paginated results.
* **Filter Class Addition**:
- Added a new class `warehouseFilter` with properties for filtering warehouses by various attributes such as `Id`, `Code`, `Name`, `Address`, `Zip`, `City`, `Province`, and `Country`.
* **Paginated Endpoint**:
- Introduced a new endpoint `GetAllItems` in the `WarehouseController` class to handle paginated and filtered retrieval of warehouses. This endpoint includes user role validation, filtering logic based on the `warehouseFilter` class, and pagination logic.
=> warehouses working filter plus pagination

PythonTests/test_items.py, PythonTests/test_orders.py, V2/Cargohub/controllers/itemcontroller.cs, V2/Cargohub/controllers/ordercontroller.cs, V2/tests/itemsTests.cs, V2/tests/ordersTests.cs
This pull request includes several changes to the `V2/Cargohub/controllers/itemcontroller.cs` file and updates to the corresponding tests in `V2/tests/itemsTests.cs`. The changes focus on modifying the `GetAllItems` method and ensuring the tests reflect these modifications.
Changes to `GetAllItems` method:
* [`V2/Cargohub/controllers/itemcontroller.cs`](diffhunk://#diff-10d20dd6649e70fb1da4e0ebdcd3e8431fcf42f8407f17028bf186bfcf21387fL114-R114): Removed the specific route for the `HttpGet` attribute to allow for more flexible routing.
* [`V2/Cargohub/controllers/itemcontroller.cs`](diffhunk://#diff-10d20dd6649e70fb1da4e0ebdcd3e8431fcf42f8407f17028bf186bfcf21387fL128-R131): Added a check to initialize `tofilter` if it is null.
* [`V2/Cargohub/controllers/itemcontroller.cs`](diffhunk://#diff- …
=> working refactored httpget and test

PythonTests/test_shipments.py, V2/Cargohub/controllers/shipmentcontroller.cs, V2/tests/shipmentsTests.cs
This pull request includes changes to both the test suite and the shipment controller to improve functionality and update test methods. The most important changes include splitting the test method for shipments into two separate methods for different API versions, updating the `GetAllShipments` method in the shipment controller, and modifying the test method to accommodate the new pagination feature.
Improvements to test suite:
* [`PythonTests/test_shipments.py`](diffhunk://#diff-80fce5f32abd55ce414dc884826b560ab79293060fa0119080d5b6226f6f2521L12-R20): Split the `test_get_shipments` method into `test_get_shipments_v1` and `test_get_shipments_v2` to separately test different API versions.
Updates to shipment controller:
* [`V2/Cargohub/controllers/shipmentcontroller.cs`](diffhunk://#diff-79 …
=> working refactored tests and controller

.github/workflows/main.yml
This pull request includes changes to improve the efficiency of the CI/CD pipeline by adding caching for dependencies in the `.github/workflows/main.yml` file. The most important changes are as follows:
Enhancements to CI/CD pipeline:
* Added caching for .NET dependencies to speed up the build process by using the `actions/cache@v3` action and specifying the cache path and keys. This change applies when the language is C#. (`[.github/workflows/main.ymlR33-R46](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R33-R46)`)
* Added caching for Python dependencies to optimize the installation process by using the `actions/cache@v3` action and specifying the cache path and keys. (`[.github/workflows/main.ymlR135-R142](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e …
=> 385 dependency caching for faster builds

PythonTests/test_ItemGroups.py, PythonTests/test_ItemLines.py, PythonTests/test_Items.py, V1/Cargohub/data/item_groups.json, V1/Cargohub/data/item_lines.json, V1/Cargohub/services/ItemGroupService.cs, V2/Cargohub/data/item_groups.json, V2/Cargohub/data/item_lines.json
This pull request includes multiple changes across different test files to improve the handling of item groups and item lines in the test cases. The most important changes include adding checks for the existence of item groups and item lines before performing update and delete operations, and renaming test methods for better organization.
* [`PythonTests/test_ItemGroups.py`](diffhunk://#diff-baf1a30319b779048731c2996c6e86c295db7dd4c48bf35a4a39dd715577dea2R88-R116): Added checks to ensure item groups exist before attempting to update or delete them in `test_05_put_item_group_id` and `test_06_delete_item_group_id` methods. [[1]](diffhunk://#diff-baf1a30319b779048731c2996c6e86c295db7dd4c48bf35a4a39dd715577dea2R88-R116) [[2]](diffhunk://#diff-baf1a30319b779048731c2996c6e86c295db7dd4c48bf35a4a3 …
=> 382 test itemspy sorted the test in the right order

PythonTests/test_Locations.py
This pull request includes changes to the `PythonTests/test_Locations.py` file to improve the handling of location-related tests. The most important changes involve modifying the test methods to dynamically use the last location ID instead of hardcoded values, ensuring more robust and flexible tests.
Improvements to test methods:
* [`test_create_location`](diffhunk://#diff-ca0258daa46f1efadee91d0f5a3fbb23feb0f2732afcdb951e11de6d61aa96d8L12-R25): Changed the test method to create a new location and verify the response status code is 201.
* [`test_get_locations`](diffhunk://#diff-ca0258daa46f1efadee91d0f5a3fbb23feb0f2732afcdb951e11de6d61aa96d8L28-R51): Modified the test method to retrieve the list of locations and dynamically get the last location ID for subsequent tests.
* …
=> 391 test locationspy sorted the test in the right order

.github/workflows/main.yml
This pull request reorganizes the steps in the GitHub Actions workflow configuration file `.github/workflows/main.yml` to improve the setup and execution order for .NET and Python environments.
Reorganization of GitHub Actions workflow:
* Moved the `.NET` setup step to follow the dependency caching step for better organization and efficiency. [[1]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L23-L29) [[2]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R32-L43)
* Reordered the `Run application` step to follow the `Install Python dependencies` step to ensure dependencies are installed before running the application. [[1]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L120-L131) …
=> 385 dependency caching for faster builds 2

.github/workflows/main.yml, V2/Cargohub/Authentication/ApiKey.cs, V2/Cargohub/controllers/InventoryController.cs, V2/Cargohub/controllers/ItemController.cs, V2/Cargohub/controllers/LocationController.cs, V2/Cargohub/controllers/OrderController.cs, V2/Cargohub/data/apikeys.json, V2/Cargohub/services/IIventoryService.cs, V2/Cargohub/services/InventoryService.cs, V2/Cargohub/services/WarehouseService.cs, V2/tests/InventoryTests.cs, V2/tests/ItemTests.cs, V2/tests/LocationTests.cs, V2/tests/OrderTests.cs
This pull request includes several changes to the `V2/Cargohub` project, focusing on refactoring and improving the handling of `WarehouseID` as a string, enhancing the filtering and retrieval of inventories, items, and orders based on warehouse locations, and updating the API key storage.
**Refactoring and Enhancements:**
* Changed the type of `WarehouseID` from `int` to `string` in `ApiKeyModel` to support multiple warehouse IDs. (`V2/Cargohub/Authentication/ApiKey.cs`)
* Updated the `inventoryFilter` class and `InventoryController` to handle `WarehouseID` as a string and added logic to filter inventories based on warehouse locations. (`V2/Cargohub/controllers/InventoryController.cs`)
* Added `ILocationService` to `ItemController` and implemented filtering of items based on warehouse …
=> 371 make the api keys strings

PythonTests/test_Items.py, PythonTests/test_Orders.py, V1/Cargohub/controllers/OrderController.cs, V1/Cargohub/services/IOrderService.cs, V1/Cargohub/services/OrderService.cs, V2/Cargohub/controllers/OrderController.cs, V2/Cargohub/services/IOrderService.cs, V2/Cargohub/services/OrderService.cs
This pull request includes significant changes to the test suite and the `OrderController` in both versions of the Cargohub API. The most important changes include the addition of new test cases, refactoring of existing test cases, and updates to the `OrderController` to support new endpoints and improve functionality.
* Added new test cases for creating, updating, and deleting orders in `PythonTests/test_Orders.py` to improve coverage and ensure the API handles various scenarios correctly. [[1]](diffhunk://#diff-8b894e8f6b5656df543baaed3b458549b4498461bf060fb944c78aef6aee61c7R51-R218) [[2]](diffhunk://#diff-8b894e8f6b5656df543baaed3b458549b4498461bf060fb944c78aef6aee61c7L158-R282)
* Removed redundant print statements from `PythonTests/test_Items.py` to clean up the test output.
* …
=> 394 test orderspy sorted the test in the right order

PythonTests/test_Clients.py, PythonTests/test_Inventories.py, PythonTests/test_Shipments.py, V2/Cargohub/controllers/ShipmentController.cs
This pull request includes changes to several test files and a controller file to improve the accuracy and robustness of the tests and to handle edge cases in pagination logic. The most important changes include updating test cases to use the correct client and inventory IDs, removing unnecessary steps in shipment deletion tests, and adding pagination boundary checks.
Improvements to test cases:
* [`PythonTests/test_Clients.py`](diffhunk://#diff-ee4b8cbbbb44afa29488db569813c9a2f633db384aa3cfcdcebc75840216a9a6R255-R260): Updated `test_06_createV1_getV2_test` to use `created_client_id` instead of `last_client_id` for fetching and deleting clients. [[1]](diffhunk://#diff-ee4b8cbbbb44afa29488db569813c9a2f633db384aa3cfcdcebc75840216a9a6R255-R260) …
=> 420 test shipment bug fixes

PythonTests/test_Locations.py
This pull request includes significant updates to the CI/CD workflows and introduces new Python tests for clients and inventories. The key changes are as follows:
* Consolidated the CI workflows by removing `.github/workflows/csharp-app.yml` and introducing `.github/workflows/main.yml` with separate jobs for C# and Python tests. This includes caching dependencies, setting up environments, running builds, tests, and generating coverage reports for both C# and Python projects. [[1]](diffhunk://#diff-4da376eea0f828fce1d3a28b09b8c91069dc91099b60e2ed6ae60a189e42d5acL1-L50) [[2]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R1-R173)
* Added a new daily maintenance workflow in `.github/workflows/maintenance.yml` to remove old artifacts.
* Added new …
=> Locations pytest create in v1 get & delete in v2 #431

V2/Cargohub/Authentication/ApiKey.cs, V2/Cargohub/Authentication/ApiKeyMiddleware.cs, V2/Cargohub/Authentication/AuthConstants.cs, V2/Cargohub/Program.cs, V2/Cargohub/controllers/AdminController.cs, V2/Cargohub/services/AdminService.cs, V2/Cargohub/services/IAdminService.cs, V2/Cargohub/services/WarehouseService.cs, V2/tests/AdminTests.cs
This pull request includes several changes to the `V2/Cargohub` project to improve the authentication system and introduce new functionality for updating API keys. The most important changes involve namespace updates, modifications to the `ApiKeyStorage` class, and the addition of new methods and tests for updating API keys.
* Updated namespaces in `ApiKey.cs`, `ApiKeyMiddleware.cs`, `AuthConstants.cs`, `Program.cs`, `AdminController.cs`, `AdminService.cs`, `IAdminService.cs`, and `WarehouseService.cs` to `ServicesV2`. [[1]](diffhunk://#diff-a5a042a900bb714956b7e980d5d879cb015d45177a734fcdb8e770a0e5c46527L3-R3) [[2]](diffhunk://#diff-eec58533aeb4a795a9af4d945bb0d9eee083a64feb9d65ca6f85067ec58d29b6L1-R14) [[3]](diffhunk://#diff-074206a9dcab2e802663d048dcde07d93551ca44735e3b8d773da6d59457514 …
=> 436 the system must provide an endpoint for editing apikeys

V2/Cargohub/controllers/InventoryController.cs, V2/Cargohub/services/IIventoryService.cs, V2/Cargohub/services/InventoryService.cs, V2/tests/InventoryTests.cs
This pull request includes several changes to `V2/Cargohub` to enhance the inventory management functionality, specifically focusing on the patching mechanism and access control.
* [`V2/Cargohub/controllers/InventoryController.cs`](diffhunk://#diff-fa48d124554de047b736b03b8d7272a2166198dbbf77bd9e71c1bea924928408L311-R326): Updated the `PatchInventory` method to take a property name and new value as parameters, and added role-based access control to restrict access to certain user roles.
* [`V2/Cargohub/services/IIventoryService.cs`](diffhunk://#diff-377a0a6b09542c6d9fd704bab8bb5c2a56fb2fa2f7d1c336cbff6283cc24e3b1L13-R13): Modified the `PatchInventory` method in the `IInventoryService` interface to accept a property name and new value, instead of an `InventoryCS` object.
* …
=> functions and test works

V2/Cargohub/controllers/InventoryController.cs, V2/tests/InventoryTests.cs
This pull request includes changes to the `InventoryController` and its corresponding unit tests to handle unauthorized access more effectively. The most important changes include modifying the `GetAllInventories` method to return a generic `Unauthorized` result and updating various test methods to include checks for unauthorized access.
Changes to `InventoryController`:
* [`V2/Cargohub/controllers/InventoryController.cs`](diffhunk://#diff-fa48d124554de047b736b03b8d7272a2166198dbbf77bd9e71c1bea924928408L74-R74): Modified the `GetAllInventories` method to return a generic `Unauthorized` result instead of passing the `userRole` parameter.
Updates to unit tests:
* [`V2/tests/InventoryTests.cs`](diffhunk://#diff-167205bc7480103842f611ded26e1b274aabb3d6c23edce9e30aea099662db34R56-R69): Updated …
=> 467 adding unauthorized to the inventory test

.github/workflows/main.yml
This pull request includes several updates to the `.github/workflows/main.yml` file, focusing on improving the handling of code coverage reports and cleaning up the setup process. The most important changes include removing unnecessary installation directory settings, cleaning up commented-out code in the coverage report summary, and ensuring coverage data is written to the GitHub step summary.
Code coverage improvements:
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R104-R107): Added lines to write the total percentage covered and the message "No coverage data found" to the GitHub step summary for better visibility in the workflow logs.
Setup process cleanup:
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1c …
=> 465 coverage percentage 3

V2/tests/TransferTests.cs
This pull request includes several updates to the test methods in the `V2/tests/TransferTests.cs` file. The changes primarily add checks for unauthorized access when the user role is set to "User". These checks ensure that the methods return a 401 Unauthorized status code when the user does not have the proper permissions.
Authorization checks added to test methods:
* [`GetTransferByIdTest_Exists()`](diffhunk://#diff-f4a787110f79b247e05bd56561626d38b7a00b2c91407fef6d72a92820e5bd8fR83-R96): Added checks for unauthorized access when fetching all transfers.
* [`GetTransferByIdTest_WrongId()`](diffhunk://#diff-f4a787110f79b247e05bd56561626d38b7a00b2c91407fef6d72a92820e5bd8fR119-R132): Added checks for unauthorized access when fetching a transfer by ID.
* …
=> unauthorized test transfer done

PythonTests/test_Inventories.py, V2/Cargohub/controllers/InventoryController.cs, V2/Cargohub/controllers/ItemController.cs, V2/Cargohub/controllers/WarehouseController.cs, V2/tests/InventoryTests.cs, V2/tests/ItemTests.cs
This pull request includes significant changes to the `InventoryController`, `ItemController`, and `WarehouseController` classes, as well as their corresponding test files. The changes focus on enhancing authorization checks, improving pagination logic, and refactoring code for better readability and maintainability.
* [`V2/Cargohub/controllers/ItemController.cs`](diffhunk://#diff-84a6afb31e0caa6259fcf31d2219c9ae3123ac4490ce4bd2e60cead4eec0cd7dR304-R310): Added authorization checks to ensure only users with specific roles can update items.
* [`V2/Cargohub/controllers/WarehouseController.cs`](diffhunk://#diff-70ec61fbf0bac5d4101ed52879eb083dee641e8b7efd8bd175dd973951bcc78bL216-R228): Implemented role-based authorization for patching warehouse information.
* …
=> Adding unauthorized to the items test

V2/tests/ShipmentTests.cs
This pull request includes changes to the `V2/tests/ShipmentTests.cs` file to add authorization checks for various shipment-related test methods. The changes ensure that the tests verify the behavior when the user does not have the necessary permissions.
Authorization checks added to test methods:
* [`public void GetShipmentsTest_Exists()`](diffhunk://#diff-39a3ff3a920c7e241c450e8ea60548523c2b76fa7bfbe997d5090574763b3bf9R52-R65): Added code to simulate an unauthorized user and verify that the `GetAllShipments` method returns a 401 Unauthorized status.
* [`public void GetShipmentByIdTest_Exists()`](diffhunk://#diff-39a3ff3a920c7e241c450e8ea60548523c2b76fa7bfbe997d5090574763b3bf9R97-R110): Added code to simulate an unauthorized user and verify that the `GetShipmentById` method returns a 401 …
=> test shipments done

.github/workflows/main.yml, V2/Cargohub/services/ClientService.cs, V2/tests/ClientTests.cs
This pull request includes several changes to the `ClientService` and its associated tests. The most important changes include adding new test methods for various client service operations, modifying the client update logic, and updating the GitHub Actions workflow configuration.
* [`V2/tests/ClientTests.cs`](diffhunk://#diff-c6ad61f58fb4d4f49de621acc3371472b3d8c7723b77535b49cecfe9c0855518R428-R640): Added multiple test methods to cover various client service operations such as getting all clients, getting a client by ID, creating a client, creating multiple clients, updating a client, deleting a client, deleting multiple clients, and patching a client.
* [`V2/Cargohub/services/ClientService.cs`](diffhunk://#diff-3070681823f3002acdd8ee205982a0efcbcb080100daaa5261ff23d674fab525L64-R64): …
=> 501 increasing code coverage clienttest v2

V2/tests/ShipmentTests.cs
This pull request introduces several enhancements and new tests to the `V2/tests/ShipmentTests.cs` file. The changes focus on adding JSON serialization for shipment data, initializing test data, and expanding the test coverage for various shipment service methods.
Key changes include:
* Added `Newtonsoft.Json` to handle JSON serialization and deserialization in the test setup.
* Enhanced the `Setup` method to create and write shipment data to a JSON file, ensuring the test environment is properly initialized.
* Added multiple test methods to cover the core functionalities of the `ShipmentService`, including:
* `GetAllShipmentsService_Test` to verify retrieval of all shipments. (F5aa4798L562R568)
* `GetShipmentByIdService_Test` to verify retrieval of a shipment by ID. (F5aa4798L569R577)
* …
=> Increase code coverage for ItemLineService tests

.github/workflows/main.yml, V1/Cargohub/services/ClientService.cs, V1/tests/ClientTests.cs, V1/tests/tests.csproj
This pull request includes several changes to improve the functionality and testing of the `ClientService` in the `V1` project. The most important changes include updating the method used to find a client, adding new dependencies to the test project, and enhancing the test cases with additional setup and test methods.
* Changed the method used to find a client from `Single` to `FirstOrDefault` in `UpdateClient` to handle cases where the client may not exist. (`V1/Cargohub/services/ClientService.cs`)
* Added new dependencies (`Microsoft.Extensions.Logging` and `Newtonsoft.Json`) to the test project to support logging and JSON operations. (`V1/tests/ClientTests.cs`)
* Enhanced the `Setup` method to initialize a sample client and write it to a JSON file for testing purposes. …
=> 500 increase client service coverage v1

V2/Cargohub/services/TransferService.cs, V2/tests/InventoryTests.cs, V2/tests/TransferTests.cs
This pull request includes several changes to the `TransferService` and related test cases, focusing on enhancing the functionality and improving the test coverage. The most important changes include modifying the `UpdateTransfer` method, adding JSON data setup for tests, and introducing new test methods for various service functionalities.
* [`V2/Cargohub/services/TransferService.cs`](diffhunk://#diff-f506971b7819f0bc665f095fd8dec877eddc2d916b1bce41b2de9b56fe7a71fdL74-R74): Modified `UpdateTransfer` method to use `FirstOrDefault` instead of `Single` to handle cases where no transfer matches the given ID.
* [`V2/tests/InventoryTests.cs`](diffhunk://#diff-167205bc7480103842f611ded26e1b274aabb3d6c23edce9e30aea099662db34R26-R53): Added JSON data setup in the `Setup` method to initialize test …
=> Increased the code coverage for TransferService V2

V2/tests/InventoryTests.cs, V2/tests/TransferTests.cs
This pull request adds several new test methods to the `InventoryTests.cs` file and comments out an existing test method in the `TransferTests.cs` file. The new tests cover various functionalities of the `InventoryService`, including creating, updating, and deleting inventories, as well as fetching inventories by different criteria.
New test methods in `InventoryTests.cs`:
* Added `GetAllInventoriesService_Test` to test fetching all inventories.
* Added `GetInventoryByIdService_Test` to test fetching an inventory by its ID.
* Added `CreateInventoryService_Test` to test creating a new inventory.
* Added `UpdateInventoryByIdService_Test` to test updating an inventory by its ID.
* Added `DeleteInventoryService_Test` to test deleting an inventory by its ID.
Changes in `TransferTests.cs`:
* …
=> 530 increased code coverage for inventoryservicesv2

.github/workflows/main.yml, V2/Cargohub/services/LocationService.cs, V2/tests/LocationTests.cs, V2/tests/SupplierTests.cs
This pull request includes several updates to the `LocationService` and corresponding test cases in the `LocationTests` file. The changes improve error handling, add new test methods, and remove commented-out code in the `SupplierTests` file.
Error handling improvements:
* [`V2/Cargohub/services/LocationService.cs`](diffhunk://#diff-341630c11096a3314a961e0fc1329cfdf95df23377858baec205875650f20533L70-R70): Changed `Single` to `SingleOrDefault` in `UpdateLocation` to handle cases where no matching location is found.
* [`V2/Cargohub/services/LocationService.cs`](diffhunk://#diff-341630c11096a3314a961e0fc1329cfdf95df23377858baec205875650f20533R95-R97): Added a null check in `PatchLocation` to return null if the location is not found.
New test methods:
* …
=> 532 location services v2 tests

V2/tests/InventoryTests.cs
This pull request introduces several updates to the `V2/tests/InventoryTests.cs` file, primarily focusing on adding new test cases and modifying existing ones to improve test coverage and accuracy. The most important changes include the addition of new test methods for various scenarios, updates to existing test assertions, and restructuring of test data.
* Added new test method `GetInventoriesTest_Exists_filtered` to test the filtering functionality of the `GetAllInventories` method.
* Added new test method `GetInventoryTotalByItemIdTest_NotFound` to handle the scenario where an inventory item is not found.
* Added new test method `CreateInventory_ReturnsCreatedAtActionResult_WithoutInventory` to test the creation of an inventory with null input.
* Added new test method …
=> 534 increasing code coverage for InventoryControllerV2

V1/Cargohub/controllers/ItemGroupController.cs, V1/Cargohub/services/IItemGroupService.cs, V1/Cargohub/services/ItemGroupService.cs, V1/tests/ItemGroupTests.cs, V2/tests/ClientTests.cs
This pull request introduces several changes to the `V1/tests/ItemGroupTests.cs` file, primarily focusing on adding new test methods and setting up test data for the `ItemGroupService`. The most significant changes include the addition of necessary using directives, setup of test data, and implementation of various test methods.
* [`V1/tests/ItemGroupTests.cs`](diffhunk://#diff-66e9fd71de9f5a538913f0b7c711d50e94b8db9049f609f8e8b3b21a791ff3f2R9-R10): Added necessary using directives for `Newtonsoft.Json` and `System.Security.Cryptography.X509Certificates`.
* [`public void Setup()`](diffhunk://#diff-66e9fd71de9f5a538913f0b7c711d50e94b8db9049f609f8e8b3b21a791ff3f2R25-R95): Enhanced the setup method to include the creation and serialization of test data for `ItemGroupCS`.
* [`public void …
=> 526 increasing code coverage itemgroupservice v1

V1/tests/ShipmentTests.cs
This pull request introduces several new unit tests and setup modifications to the `V1/tests/ShipmentTests.cs` file. The changes include the addition of JSON serialization for shipment data, new test methods for various shipment service operations, and enhancements to the test setup.
* Added JSON serialization for shipment data in the `Setup` method to create a test data file (`[V1/tests/ShipmentTests.csR22-R61](diffhunk://#diff-0da8a5874f9929cbbeecb1d234a5a41cf27d5ecc1d50c0530b1f7ee83f3f999eR22-R61)`).
* Added multiple test methods to cover shipment service operations such as getting all shipments, getting a shipment by ID, creating a shipment, updating a shipment, deleting a shipment, and managing items within a shipment (`[V1/tests/ShipmentTests.csR252-R445](diffhunk://#diff-0da8a5874f9 …
=> Increasing code coverage for Shipment v1

V1/tests/ItemGroupTests.cs, V1/tests/ItemTypeTests.cs
This pull request includes several changes to the test files `ItemGroupTests.cs` and `ItemTypeTests.cs` to improve code readability and add new test cases for the `ItemTypeService`. The most important changes include adding proper formatting to the existing tests, adding new test methods for `ItemTypeService`, and ensuring the creation of necessary directories and files for testing.
Improvements to code readability:
* [`V1/tests/ItemGroupTests.cs`](diffhunk://#diff-66e9fd71de9f5a538913f0b7c711d50e94b8db9049f609f8e8b3b21a791ff3f2L26-R27): Added proper formatting to the test methods and object initializations for better readability. [[1]](diffhunk://#diff-66e9fd71de9f5a538913f0b7c711d50e94b8db9049f609f8e8b3b21a791ff3f2L26-R27) [[2]](diffhunk://#diff-66e9fd71de9f5a538913f0b7c711d50e94b8db9049 …
=> increasing the code coverage for itemtypeservice v1

V2/Cargohub/controllers/ItemController.cs, V2/tests/ItemTests.cs, V2/tests/LocationTests.cs
This pull request includes several changes to the `ItemController` and related tests to improve error handling and add new test cases. The most important changes include adding null checks and handling for empty collections, as well as adding new test methods to cover various scenarios.
* [`V2/Cargohub/controllers/ItemController.cs`](diffhunk://#diff-84a6afb31e0caa6259fcf31d2219c9ae3123ac4490ce4bd2e60cead4eec0cd7dR57-R63): Added null checks and handling for empty collections in the `GetAllItems` method to return appropriate `NotFound` responses. [[1]](diffhunk://#diff-84a6afb31e0caa6259fcf31d2219c9ae3123ac4490ce4bd2e60cead4eec0cd7dR57-R63) [[2]](diffhunk://#diff-84a6afb31e0caa6259fcf31d2219c9ae3123ac4490ce4bd2e60cead4eec0cd7dL68-R72)
* …
=> 546 increasing the code coverage for itemcontrollerv2

V1/tests/ItemTests.cs
This pull request includes significant updates to the `V1/tests/ItemTests.cs` file, adding new dependencies, initializing test data, and expanding the test coverage for the `ItemService` class. The most important changes are outlined below:
* Added `Newtonsoft.Json` dependency to `V1/tests/ItemTests.cs` to handle JSON serialization and deserialization.
* In the `Setup` method, added code to create and write a sample item to a JSON file for use in tests.
* Added multiple test methods to cover various functionalities of the `ItemService` class, including:
* [`GetAllItemsService_Test`](diffhunk://#diff-ef5c985bdb7b987950c54f70501760f70ecc6f892ac4b688de5c499133adb2f5R221-R322): Tests retrieval of all items.
* [`GetItemByIdService_Test`](diffhunk://#diff-ef5c985bdb7b987950c54f70501760f70ecc6f89 …
=> Increased the code coverage for ItemService

V1/Cargohub/services/TransferService.cs, V1/tests/InventoryTests.cs, V1/tests/TransferTests.cs
This pull request includes changes to the `TransferService` and `InventoryTests` to refactor the `CommitTransfer` method and improve code readability and consistency in the test setup.
Refactoring in `TransferService`:
* Extracted logic into a new `CommitTransferAssist` method to simplify the `CommitTransfer` method. [[1]](diffhunk://#diff-b157061492aac51f13aa343cb01e62a03ad8a3fbcdf8f21f6225c8bdf024ddb0R98-R107) [[2]](diffhunk://#diff-b157061492aac51f13aa343cb01e62a03ad8a3fbcdf8f21f6225c8bdf024ddb0L116-L124)
Improvements in `InventoryTests`:
* Reformatted the `Setup` method and test methods for better readability and consistency. [[1]](diffhunk://#diff-5ee1e0fa2f13793fca4a0fa379934c314d44bef46b2d319b1497af857c6e6e83L25-R26) [[2]](diffhunk://#diff-5ee1e0fa2f13793fca4a0fa379934c314d44bef46b2 …
=> trying to fix the transfer code coverage
